replicaCount: 1

image:
  repository: ghcr.io/rso-2024-group-12/microservice-nakup
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8085

probes:
  liveness:
    enabled: true
    path: /q/health/live
  readiness:
    enabled: true
    path: /q/health/ready

config:
  kafka:
    bootstrapServers: "nakupify-kafka-kafka-bootstrap.default.svc.cluster.local:9092"
  postgres:
    username: "nakupify"
    password: "nakupify"
    jdbcUrl: "jdbc:postgresql://nakupify-db-rw.default.svc.cluster.local:5432/nakupify"
  services:
    skladisceUrl: http://microservice-skladisce-service/v1/skladisce
    narocilaUrl: http://microservice-narocila-service/internal/orders

  grpc:
    kosarica:
      host: microservice-kosarica-service
      port: "9001"

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"